services:
  postgres:
    restart: always
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5436:5432
    volumes:
      - orders_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
  kafka:
    image: apache/kafka:latest
    hostname: kafka_produce
    container_name: kafka_produce
    ports:
      - 9092:9092
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka_produce:9093
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_produce:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: orders-kraft-cluster


  kafka-ui:
    container_name: kafka_produce-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9020:8080
    environment:
      AUTH_TYPE: DISABLED
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka_produce:29092
    depends_on: [kafka]

  orders-service:
    build:
      context: ./orders
    container_name: orders-service
    env_file:
      - ./orders/.env
    ports:
      - "8081:8081"

  payments-service:
    build:
      context: ./payments
    container_name: payment-service
    env_file:
      - ./payments/.env
    ports:
      - "8082:8082"

  notifications-service:
    build:
      context: ./notifications
    container_name: notifications-service
    env_file:
      - ./notifications/.env
    ports:
      - "8083:8083"

volumes:
  orders_pgdata:
