global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: gateway
    static_configs:
      - targets: ["gateway:8080"]

  - job_name: orders
    static_configs:
      - targets: ["orders-service:8081"]

  - job_name: payments
    static_configs:
      - targets: [ "payments-service:8082" ]

  - job_name: notifications-service
    static_configs:
      - targets: [ "notifications-service:8083" ]


